2024-07-10 23:03:52,134 INFO: 192.168.48.1 - - [10/Jul/2024 23:03:52] "[35m[1mPOST /dietas HTTP/1.1[0m" 500 - [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:03:58,583 INFO: Listagem de dietas realizada: [{'id': 20, 'firebase_uuid': 'V5nmLXsJlJRC5lvs53TxOnFPvPv1', 'horarios_refeicoes': [], 'refeicoes': []}] [in /app/app.py:76]
2024-07-10 23:03:58,585 INFO: 192.168.48.1 - - [10/Jul/2024 23:03:58] "GET /dietas HTTP/1.1" 200 - [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:05:35,191 INFO: Logging setup complete [in /app/logs/log_config.py:25]
2024-07-10 23:05:35,252 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.80.3:5001 [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:05:35,253 INFO: [33mPress CTRL+C to quit[0m [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:05:49,293 INFO: 192.168.80.1 - - [10/Jul/2024 23:05:49] "OPTIONS /dietas HTTP/1.1" 200 - [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:05:49,316 ERROR: Erro de integridade ao criar dieta: (pymysql.err.IntegrityError) (1062, "Duplicate entry 'V5nmLXsJlJRC5lvs53TxOnFPvPv1' for key 'dietas.firebase_uuid'")
[SQL: INSERT INTO dietas (firebase_uuid) VALUES (%(firebase_uuid)s)]
[parameters: {'firebase_uuid': 'V5nmLXsJlJRC5lvs53TxOnFPvPv1'}]
(Background on this error at: https://sqlalche.me/e/20/gkpj) [in /app/app.py:63]
2024-07-10 23:05:49,318 INFO: 192.168.80.1 - - [10/Jul/2024 23:05:49] "[35m[1mPOST /dietas HTTP/1.1[0m" 500 - [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:05:56,624 INFO: Listagem de dietas realizada: [{'id': 20, 'firebase_uuid': 'V5nmLXsJlJRC5lvs53TxOnFPvPv1', 'horarios_refeicoes': [], 'refeicoes': []}] [in /app/app.py:76]
2024-07-10 23:05:56,625 INFO: 192.168.80.1 - - [10/Jul/2024 23:05:56] "GET /dietas HTTP/1.1" 200 - [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:06:02,589 INFO: Dieta com ID 20 deletada com sucesso. [in /app/app.py:92]
2024-07-10 23:06:02,590 INFO: 192.168.80.1 - - [10/Jul/2024 23:06:02] "DELETE /dietas/20 HTTP/1.1" 200 - [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:06:06,664 INFO: Listagem de dietas realizada: [] [in /app/app.py:76]
2024-07-10 23:06:06,665 INFO: 192.168.80.1 - - [10/Jul/2024 23:06:06] "GET /dietas HTTP/1.1" 200 - [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:06:14,241 INFO: 192.168.80.1 - - [10/Jul/2024 23:06:14] "OPTIONS /dietas HTTP/1.1" 200 - [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:06:14,256 ERROR: Erro desconhecido ao criar dieta: 'DietaCreate' object has no attribute 'horarios_refeicoes' [in /app/app.py:67]
2024-07-10 23:06:14,257 INFO: 192.168.80.1 - - [10/Jul/2024 23:06:14] "[35m[1mPOST /dietas HTTP/1.1[0m" 500 - [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:06:21,091 INFO: Listagem de dietas realizada: [{'id': 22, 'firebase_uuid': 'V5nmLXsJlJRC5lvs53TxOnFPvPv1', 'horarios_refeicoes': [], 'refeicoes': []}] [in /app/app.py:76]
2024-07-10 23:06:21,093 INFO: 192.168.80.1 - - [10/Jul/2024 23:06:21] "GET /dietas HTTP/1.1" 200 - [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:09:17,245 INFO: Logging setup complete [in /app/logs/log_config.py:25]
2024-07-10 23:09:17,309 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.96.3:5001 [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:09:17,311 INFO: [33mPress CTRL+C to quit[0m [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:09:51,318 INFO: Listagem de dietas realizada: [{'id': 22, 'firebase_uuid': 'V5nmLXsJlJRC5lvs53TxOnFPvPv1', 'horarios_refeicoes': [], 'refeicoes': []}] [in /app/app.py:78]
2024-07-10 23:09:51,319 INFO: 192.168.96.1 - - [10/Jul/2024 23:09:51] "GET /dietas HTTP/1.1" 200 - [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:09:55,919 INFO: Dieta com ID 22 deletada com sucesso. [in /app/app.py:94]
2024-07-10 23:09:55,920 INFO: 192.168.96.1 - - [10/Jul/2024 23:09:55] "DELETE /dietas/22 HTTP/1.1" 200 - [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:10:00,228 INFO: Listagem de dietas realizada: [] [in /app/app.py:78]
2024-07-10 23:10:00,229 INFO: 192.168.96.1 - - [10/Jul/2024 23:10:00] "GET /dietas HTTP/1.1" 200 - [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:10:03,118 INFO: 192.168.96.1 - - [10/Jul/2024 23:10:03] "OPTIONS /dietas HTTP/1.1" 200 - [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:10:03,132 ERROR: Erro desconhecido ao criar dieta: 'DietaCreate' object has no attribute 'horarios_refeicoes' [in /app/app.py:69]
2024-07-10 23:10:03,133 INFO: 192.168.96.1 - - [10/Jul/2024 23:10:03] "[35m[1mPOST /dietas HTTP/1.1[0m" 500 - [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:10:16,456 INFO: Listagem de dietas realizada: [{'id': 23, 'firebase_uuid': 'V5nmLXsJlJRC5lvs53TxOnFPvPv1', 'horarios_refeicoes': [], 'refeicoes': []}] [in /app/app.py:78]
2024-07-10 23:10:16,457 INFO: 192.168.96.1 - - [10/Jul/2024 23:10:16] "GET /dietas HTTP/1.1" 200 - [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:14:07,975 INFO: Logging setup complete [in /app/logs/log_config.py:25]
2024-07-10 23:14:08,035 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.112.3:5001 [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:14:08,037 INFO: [33mPress CTRL+C to quit[0m [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:14:11,641 INFO: 192.168.112.1 - - [10/Jul/2024 23:14:11] "OPTIONS /dietas HTTP/1.1" 200 - [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:14:11,663 ERROR: Erro de integridade ao criar dieta: (pymysql.err.IntegrityError) (1062, "Duplicate entry 'V5nmLXsJlJRC5lvs53TxOnFPvPv1' for key 'dietas.firebase_uuid'")
[SQL: INSERT INTO dietas (firebase_uuid) VALUES (%(firebase_uuid)s)]
[parameters: {'firebase_uuid': 'V5nmLXsJlJRC5lvs53TxOnFPvPv1'}]
(Background on this error at: https://sqlalche.me/e/20/gkpj) [in /app/app.py:65]
2024-07-10 23:14:11,664 INFO: 192.168.112.1 - - [10/Jul/2024 23:14:11] "[35m[1mPOST /dietas HTTP/1.1[0m" 500 - [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:14:21,271 INFO: Dieta com ID 23 deletada com sucesso. [in /app/app.py:94]
2024-07-10 23:14:21,273 INFO: 192.168.112.1 - - [10/Jul/2024 23:14:21] "DELETE /dietas/23 HTTP/1.1" 200 - [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:14:24,871 INFO: Listagem de dietas realizada: [] [in /app/app.py:78]
2024-07-10 23:14:24,872 INFO: 192.168.112.1 - - [10/Jul/2024 23:14:24] "GET /dietas HTTP/1.1" 200 - [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:14:26,686 INFO: 192.168.112.1 - - [10/Jul/2024 23:14:26] "OPTIONS /dietas HTTP/1.1" 200 - [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:14:26,701 INFO: Dieta criada com sucesso: {'id': 25, 'firebase_uuid': 'V5nmLXsJlJRC5lvs53TxOnFPvPv1', 'horarios_refeicoes': [], 'refeicoes': []} [in /app/app.py:39]
2024-07-10 23:14:26,702 ERROR: Erro desconhecido ao criar dieta: 'DietaCreate' object has no attribute 'horarios_refeicoes' [in /app/app.py:69]
2024-07-10 23:14:26,704 INFO: 192.168.112.1 - - [10/Jul/2024 23:14:26] "[35m[1mPOST /dietas HTTP/1.1[0m" 500 - [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:14:32,309 INFO: Listagem de dietas realizada: [{'id': 25, 'firebase_uuid': 'V5nmLXsJlJRC5lvs53TxOnFPvPv1', 'horarios_refeicoes': [], 'refeicoes': []}] [in /app/app.py:78]
2024-07-10 23:14:32,310 INFO: 192.168.112.1 - - [10/Jul/2024 23:14:32] "GET /dietas HTTP/1.1" 200 - [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:15:10,197 INFO: 192.168.112.1 - - [10/Jul/2024 23:15:10] "OPTIONS /dietas HTTP/1.1" 200 - [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:15:10,209 ERROR: Erro de integridade ao criar dieta: (pymysql.err.IntegrityError) (1062, "Duplicate entry 'V5nmLXsJlJRC5lvs53TxOnFPvPv1' for key 'dietas.firebase_uuid'")
[SQL: INSERT INTO dietas (firebase_uuid) VALUES (%(firebase_uuid)s)]
[parameters: {'firebase_uuid': 'V5nmLXsJlJRC5lvs53TxOnFPvPv1'}]
(Background on this error at: https://sqlalche.me/e/20/gkpj) [in /app/app.py:65]
2024-07-10 23:15:10,211 INFO: 192.168.112.1 - - [10/Jul/2024 23:15:10] "[35m[1mPOST /dietas HTTP/1.1[0m" 500 - [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:18:03,158 ERROR: Erro de integridade ao criar dieta: (pymysql.err.IntegrityError) (1062, "Duplicate entry 'V5nmLXsJlJRC5lvs53TxOnFPvPv1' for key 'dietas.firebase_uuid'")
[SQL: INSERT INTO dietas (firebase_uuid) VALUES (%(firebase_uuid)s)]
[parameters: {'firebase_uuid': 'V5nmLXsJlJRC5lvs53TxOnFPvPv1'}]
(Background on this error at: https://sqlalche.me/e/20/gkpj) [in /app/app.py:65]
2024-07-10 23:18:03,160 INFO: 192.168.112.1 - - [10/Jul/2024 23:18:03] "[35m[1mPOST /dietas HTTP/1.1[0m" 500 - [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
